name: drug-viability
channels:
  - conda-forge
dependencies:
  - conda-forge::python
  - conda-forge::pandas>=1.5
  - conda-forge::plotnine>=0.10.1
  - conda-forge::jupyter
  - conda-forge::jupyterlab
  - conda-forge::ipykernel
  - conda-forge::nb_conda_kernels
  - conda-forge::jupyter_contrib_nbextensions